// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectSem3withTeam.Models;

namespace ProjectSem3withTeam.Migrations
{
    [DbContext(typeof(ProjectSem3withTeamContext))]
    [Migration("20181107073153_Addseederall")]
    partial class Addseederall
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectSem3withTeam.Models.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("StudentRollNumber");

                    b.Property<int>("SubjectId");

                    b.Property<int>("SubjectMark");

                    b.Property<int>("TeacherId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("StudentRollNumber");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Mark");

                    b.HasData(
                        new { Id = 1, CreatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 866, DateTimeKind.Local), StudentRollNumber = "A001", SubjectId = 1, SubjectMark = 63, TeacherId = 1, UpdatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 866, DateTimeKind.Local) },
                        new { Id = 2, CreatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 867, DateTimeKind.Local), StudentRollNumber = "A002", SubjectId = 2, SubjectMark = 45, TeacherId = 1, UpdatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 867, DateTimeKind.Local) },
                        new { Id = 3, CreatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 867, DateTimeKind.Local), StudentRollNumber = "A003", SubjectId = 3, SubjectMark = 85, TeacherId = 1, UpdatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 867, DateTimeKind.Local) },
                        new { Id = 4, CreatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 867, DateTimeKind.Local), StudentRollNumber = "A004", SubjectId = 5, SubjectMark = 95, TeacherId = 1, UpdatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 867, DateTimeKind.Local) }
                    );
                });

            modelBuilder.Entity("ProjectSem3withTeam.Models.Student", b =>
                {
                    b.Property<string>("RollNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Phone");

                    b.Property<int>("Status");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("RollNumber");

                    b.ToTable("Student");

                    b.HasData(
                        new { RollNumber = "A001", Avatar = "https://scontent.fhan5-2.fna.fbcdn.net/v/t1.0-9/43728863_918300711698721_2592658880836141056_n.jpg?_nc_cat=102&_nc_ht=scontent.fhan5-2.fna&oh=afbb930ed930627f4682eeef3d58c271&oe=5C725A56", CreatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 865, DateTimeKind.Local), Email = "quocviet.hn98@gmail.com", FirstName = "Trịnh", LastName = "Việt", Phone = "0349555602", Status = 1, UpdatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 866, DateTimeKind.Local) },
                        new { RollNumber = "A002", Avatar = "https://scontent.fhan5-7.fna.fbcdn.net/v/t1.0-9/74230_571993326151147_1564071477_n.jpg?_nc_cat=100&_nc_ht=scontent.fhan5-7.fna&oh=d47a59698c8c56599511f5bfde14c90e&oe=5C88977B", CreatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 866, DateTimeKind.Local), Email = "thanhtung.hn98@gmail.com", FirstName = "Thanh", LastName = "Tùng", Phone = "0349321324", Status = 1, UpdatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 866, DateTimeKind.Local) },
                        new { RollNumber = "A003", Avatar = "https://scontent.fhan5-6.fna.fbcdn.net/v/t1.0-9/42434595_2098209036910379_4231368300749127680_n.jpg?_nc_cat=107&_nc_ht=scontent.fhan5-6.fna&oh=60a1bf8f30a256768b5fd4af128e9932&oe=5C40E10E", CreatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 866, DateTimeKind.Local), Email = "quecong.hn98@gmail.com", FirstName = "Quế", LastName = "Công", Phone = "043243255", Status = 1, UpdatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 866, DateTimeKind.Local) },
                        new { RollNumber = "A004", Avatar = "https://scontent.fhan5-1.fna.fbcdn.net/v/t1.0-9/23380126_514878092204816_4605254026945740300_n.jpg?_nc_cat=109&_nc_ht=scontent.fhan5-1.fna&oh=d20b108d93199e0adffa8f9a425d5dc7&oe=5C405AE8", CreatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 866, DateTimeKind.Local), Email = "huongly.hn98@gmail.com", FirstName = "Hương", LastName = "Ly", Phone = "0432443243", Status = 1, UpdatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 866, DateTimeKind.Local) }
                    );
                });

            modelBuilder.Entity("ProjectSem3withTeam.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Subject");

                    b.HasData(
                        new { Id = 1, CreatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 863, DateTimeKind.Local), Description = "Dễ học.", Name = "HTML", UpdatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 864, DateTimeKind.Local) },
                        new { Id = 2, CreatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 864, DateTimeKind.Local), Description = "Khá loằng ngoằng.", Name = "Java", UpdatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 864, DateTimeKind.Local) },
                        new { Id = 3, CreatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 864, DateTimeKind.Local), Description = "Dễ hơn java 1 chút.", Name = "C#", UpdatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 864, DateTimeKind.Local) },
                        new { Id = 4, CreatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 864, DateTimeKind.Local), Description = "Dễ học.", Name = "PHP", UpdatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 864, DateTimeKind.Local) },
                        new { Id = 5, CreatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 864, DateTimeKind.Local), Description = "Chưa xác định.", Name = "ASP.NET", UpdatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 864, DateTimeKind.Local) }
                    );
                });

            modelBuilder.Entity("ProjectSem3withTeam.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<int>("Status");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Teacher");

                    b.HasData(
                        new { Id = 1, Avatar = "https://i.stack.imgur.com/EFHit.jpg?s=328&g=1", CreatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 865, DateTimeKind.Local), Email = "Xuanhung2401@gmail.com", Name = "Xuân Hùng", Phone = "012349876", Status = 1, UpdatedAt = new DateTime(2018, 11, 7, 14, 31, 52, 865, DateTimeKind.Local) }
                    );
                });

            modelBuilder.Entity("ProjectSem3withTeam.Models.Mark", b =>
                {
                    b.HasOne("ProjectSem3withTeam.Models.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentRollNumber");

                    b.HasOne("ProjectSem3withTeam.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjectSem3withTeam.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
